### ISSUE TITLE
Add Viewport (Room drag and drop)

### ISSUE THREAD

**Issue by mtwzim** [jankuss/shroom#10]
Viewport allows the drag and drop effect present in habbo rooms to be executed, but as pointed out by @jankuss it may be unnecessary in some cases. As in the "Furni Editor with a Real-Time Preview" or in the catalog.

Basically an encapsulation of the Room would be done as suggested: 
```
const room = Room.create(/* ... */);

app.stage.addChild(new RoomCamera(room));
```

**Comment by jankuss** [comment]
Closed by #19
