### ISSUE TITLE
Add loading avatar

### ISSUE THREAD

**Issue by fp07** [jankuss/shroom#114]
When avatars are loading, add the loading avatar style, for example when http requests are pending for the avatar look.
![loading-avatar](https://user-images.githubusercontent.com/59264657/105618727-f50e0800-5dea-11eb-89b6-975d18d09ddf.png)

**Comment by fp07** [comment]
This is usefull when you enter an room, with 500 avatars for example. Not all are going to load at the same time.

**Comment by fp07** [comment]
This is useful when you enter an room with 500 avatars for example. Not all are going to load at the same time.

**Comment by jankuss** [comment]
There already is the avatar loading style. It has been added in version `0.3.0`.

**Comment by fp07** [comment]
Thanks for your response. Keep up :)
