### ISSUE TITLE
Add head only for avatar

### ISSUE THREAD

**Issue by fp07** [jankuss/shroom#115]
For the messenger only the head of the avatar is useful.

**Comment by fp07** [comment]
Maybe also add small size for the head? The avatar can have small (messenger list + small head), medium and large (for rooms)

**Comment by jankuss** [comment]
> For the messenger only the head of the avatar is useful.

The `BaseAvatar` class has a `headOnly` option, which you can specify in the constructor.

> Maybe also add small size for the head? The avatar can have small (messenger list + small head), medium and large (for rooms)

We could add that, but isn't scaling an option for that?

**Comment by fp07** [comment]
On the original the small size, is an own option. I don't think scaling is done on the small avatar parts. Is it much work?

**Comment by jankuss** [comment]
Like we could do work on that, just it's not a priority right now. If you want you can create a separate issue for that so it is tracked.
