### ISSUE TITLE
Coordinates do not match Flash Client's representation of model

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#28]
Using the same floor map in both clients, the Flash client considers 3,5 in to be in the doorway, however Shroom's implementation decides it is where the avatar appears in this image.

<img width="866" alt="Screenshot 2020-12-16 at 17 22 08" src="https://user-images.githubusercontent.com/76122063/102383236-3bd63a00-3fc3-11eb-8175-0bc660c6ed9e.png">

Then, using the onTileClick function, clicking the avatar's square has position roomX: 4, roomY: 5 (not the same coordinates as specified to create the avatar).

Room map (model_a):
`xxxxxxxxxxxx
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxx00000000
xxxxxxxxxxxx
xxxxxxxxxxxx`

**Comment by jankuss** [comment]
I believe what is going on is that the current implementation of the tile parser in shroom discards "empty" rows and columns.
That means all rows/columns consisting of only `xxxxx` will be discarded.

I think it would make sense to have the same behavior as the flash client.
So the solution for shroom is to just remove the function which removes empty rows and columns.

The other problem you faced is probably related to the door logic somehow.
Will check both of these issues out.

**Comment by somekindadude** [comment]
Yes it seems changing 
`    const startIndexColumn = findFirstNonEmptyColumnIndex(tilemap);
    const startIndexRow = findFirstNonEmptyRowIndex(tilemap);`

to both be 0 will create the invisible rows, and give the right coordinates. But not always the right position for click etc

**Comment by jankuss** [comment]
It's fixed in v0.1.4
