### ISSUE TITLE
Certain clothing items throw errors

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#29]
Trying to use certain clothing items in the figure string throws an error. 

Using `ch-215-1331`, for example as the chest item (short sleved t-shirt) will cause `Invalid library h_std_ls_2_0_0 ls`

**Comment by jankuss** [comment]
Can you try with version v0.2.0? There a lot related avatars has been addressed.

**Comment by somekindadude** [comment]
There is no longer an error but the t-shirt has no sleeves.
