### ISSUE TITLE
Renaming the default branch from master to main

### ISSUE THREAD

**Issue by mtwzim** [jankuss/shroom#3]
According to the new standards preferred by git and github, which are considering using main instead of master, because "it’s short, it keeps your muscle memory intact, and it translates well across most languages", it would be interesting to rename your main branch of master to main.

You can find the documentation of what I'm talking about [here - click](https://github.com/github/renaming)

**Comment by jankuss** [comment]
Thanks for the suggestion. For now I believe we can safely stay with the `master` branch, as a change of the branch name would probably break some pipelines.

If there is less to do in the project, I'm happy to do some repository grooming.
