### ISSUE TITLE
Furniture by id or classname.

### ISSUE THREAD

**Issue by SpreedBlood** [jankuss/shroom#30]
Since the current habbo emulators don't send the furniture className but the sprite id, it would be nice to be able to create furnitures by id instead.

new Furniture({
id: 13
});
Or
new Furniture({
type: "shelves_norja"
});

**Comment by somekindadude** [comment]
Currently you can just loaded the furnidata.xml file and you are able to create a mapping yourself for the time being, if you need to.

**Comment by jankuss** [comment]
This is now possible in `v0.1.6`

```
new FloorFurniture({ id: 123, /* ... */ })
// or
new FloorFurniture({ type: "test", /* ... */ })
```
