### ISSUE TITLE
Animations pause when tab is in background

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#37]
All animations pause when the tab enters the background, meaning that when the tab is re-opened, all animations queue up and execute. 

If, say, a server is sending to move an avatar each 500ms, you get all the queued up movements execute rather than just seeing where the avatar should be at that moment in time.

**Comment by jankuss** [comment]
What would be a good way to solve this?
The browser stops executing the `requestAnimationFrame` code when the tab goes into the background.

Maybe should we disable the queuing when the tab is in the background and enable it  when the tab focuses again?

**Comment by somekindadude** [comment]
I guess one way would be to log the time of the last animation and then check with the next animation time, you can decide how many frames to skip this way. I think if you stop queueing you could still end up like 450ms delayed if the timing was wrong.

**Comment by jankuss** [comment]
> I guess one way would be to log the time of the last animation and then check with the next animation time, you can decide how many frames to skip this way. I think if you stop queueing you could still end up like 450ms delayed if the timing was wrong.

I think this is the way to go. We already do the tracking of the last time of `raf`. Just right now, we basically just consider the current movement animation instead of possibly looking ahead.

**Comment by fp07** [comment]
I think you can use the following for this: https://developer.mozilla.org/en-US/docs/Web/API/Document/hidden

**Comment by jankuss** [comment]
I think this issue will be done once we take care of #122 in the next version.
