### ISSUE TITLE
RoomPosition for bubble position

### ISSUE THREAD

**Issue by ManuelDevs** [jankuss/shroom#38]
There should be something to know the real position of the elements in the canvas for create our userstand and chat bubbles positioned correctly according to the room position.

**Comment by sindreslungaard** [comment]
You can get the screen position of the avatar with `avatar.getScreenPosition()`, this will be relative to the parent PIXI.Container position. You will have to offset it with the position of your camera/stage.

Another way to do this which works for any room object is to get the tile position and calculate the screen positions from it, just like shroom does behind the scenes (x * 32). This is also relative to any parent containers just like the previous method.

**Comment by jankuss** [comment]
We now expose the apparent position on the canvas through `screenPosition`. This will be in the next version.
