### ISSUE TITLE
Expose furniture swf data

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#41]
Some furniture interaction data is stored in the index.bin file (the logic argument). This is required for handling interaction with furniture and parsing extradata correctly. Is it possible to allow access to the item type data from the Floor/Wall Furniture classes?

**Comment by jankuss** [comment]
I planned on introducing the following API to furniture.

```ts
const furniture = new FloorFurniture({
  /* ... */
  onLoad: (extradata) => {
    if (extradata.logic === "bla") {
     furniture.onClick = () => console.log("Clicked");
    }
  }
})
```

**Comment by somekindadude** [comment]
Because it's used to handle double clicking at any point as well as generating the animation status, I am not sure if it is beneficial on load as it'd likely be needed to be used later down the line. For example, showing the status of a moodlight when the only data that is sent is it's current config, or double clicking an exchange item needing to show the prompt for redeem. 

If we register a 'on double click' event, then it would be necessary to know in that data. Unless I am missing already implemented stuff?

**Comment by jankuss** [comment]
Another option would be to expose it as a property which returns a promise.

```ts
const furni = new FloorFurniture();

const extraData = await furni.extradata;

if (extraData.logic === "bla") {
/* ... */
}
```

I think this is mildly related to #35 aswell. There we need to expose some swf data aswell.

**Comment by somekindadude** [comment]
This could work and I yes I assume most of the data the client needs is in the item swf. 

Instead of just the extra data example, the whole furniture loading process could become promise-ified as well in this case? this would potentially allow for requesting many furnitures to be loaded at once like when loading a room?

**Comment by jankuss** [comment]
This will be a bit harder since the furniture itself handles the logic of loading itself. This enables the furniture to display a placeholder image while waiting for the assets to load.

We could introduce a `load` method, which basically forces furniture to load, even before it is attached to a room.
