### ISSUE TITLE
More data from HitEvent

### ISSUE THREAD

**Issue by sindreslungaard** [jankuss/shroom#43]
Currently none of the original MouseEvent data is included in the HitEvent dispatched by shroom when clicking on furniture and avatars. It would be useful to have access to this data, especially to check whether or not it was a left, middle or right mouse button click.

Could we just add the original MouseEvent as a property to HitEvent?

**Comment by jankuss** [comment]
Yeah that makes sense and should be a pretty simple addition.

**Comment by sindreslungaard** [comment]
Great, i'll submit a pr for it later

**Comment by jankuss** [comment]
Already stole it from you :D

Added it in:
48970d62699b374f42e7629859d01e4be3ec31ec

**Comment by sindreslungaard** [comment]
nice!
