### ISSUE TITLE
Tile cursor shows under "flooring" floor items

### ISSUE THREAD

**Issue by peakrp-dev** [jankuss/shroom#48]
Shroom:

![image](https://user-images.githubusercontent.com/73438147/103174008-8f177a80-4856-11eb-84c9-b564f5772be6.png)
![image](https://user-images.githubusercontent.com/73438147/103174006-8aeb5d00-4856-11eb-8ab9-b4abdf58b401.png)

Flash:

![image](https://user-images.githubusercontent.com/73438147/103174012-9a6aa600-4856-11eb-9fcd-e26a9e4f4593.png)

(The tile cursor is a different image)

**Comment by jankuss** [comment]
I believe the fix would be, instead of adding tile cursor to a separate layer, just put it into the furniture layer aswell.
The furniture I looked at have a negative Z-Index defined, so probably that means they are positioned below the tile cursor?
