### ISSUE TITLE
Convert screen coordinates to room tile

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#52]
Need an option to convert a screen pixel position to the room tile 
e.g. for use in on mouse move when placing furni

**Comment by jankuss** [comment]
I am on something similar right now.
Would it be enough to just have a new `onActiveTileChange` event, which basically fires when you hover over an tile?

**Comment by somekindadude** [comment]
Yeah as long as you are also able to tell when you have stopped hovering by going off the edge of the room using this method too

**Comment by jankuss** [comment]
Will be in the next version then :+1:
