### ISSUE TITLE
Single Shroom instance for multiple canvases?

### ISSUE THREAD

**Issue by somekindadude** [jankuss/shroom#55]
Is it possible to be able to create a single Shroom instance and use that one for multiple PIXI applications? 

By passing the PIXI application to the Room create function instead of the Shroom create function means we can use multiple canvas without having to re-create Shroom for other instances such as preview in catalog or inventory, as well as being able to use Shroom to get furnidata information (such as file path for icon?) without creating a PIXI application.

**Comment by jankuss** [comment]
I think that that should easily be possible.
The `Shroom` instance is basically just a dependency container for the convenience, so you don't need to create every single dependency yourself.

I think, to ensure backward compatibility, we could make the `application` property in `Shroom.create` optional.
Then we add an optional  `application` property to `Room.create` aswell.

For a workaround now:
You can use the default constructor of the `Room` class.

The `Room.create` static method looks as follows.
```
  static create(shroom: Shroom, { tilemap }: CreateOptions) {
    return new Room({ ...shroom.dependencies, tilemap });
  }
```

So you coud just use the following code to use another PIXI.Application
```
return new Room({ ...shroom.dependencies, tilemap, application: otherApplication });
```
